export default function PaymentReceipt({ payment, tenant, floor, unit, buildingName, onClose }) {
  const handlePrint = () => {
    const printWindow = window.open('', '_blank')
    if (!printWindow) return
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head><title>Receipt ${payment.receiptId}</title>
      <style>
        body { font-family: 'Segoe UI', system-ui, sans-serif; max-width: 600px; margin: 40px auto; padding: 0 20px; color: #1a1a2e; }
        .header { text-align: center; border-bottom: 2px solid #1a1a2e; padding-bottom: 16px; margin-bottom: 24px; }
        .header h1 { margin: 0; font-size: 22px; letter-spacing: 1px; }
        .header p { margin: 4px 0 0; color: #666; font-size: 13px; }
        .receipt-no { text-align: right; font-size: 13px; color: #666; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; }
        td { padding: 6px 0; font-size: 14px; }
        td:last-child { text-align: right; font-weight: 500; }
        .total-row td { border-top: 2px solid #1a1a2e; padding-top: 10px; font-weight: 700; font-size: 16px; }
        .info { margin: 20px 0; padding: 14px; background: #f8f9fa; border-radius: 8px; font-size: 13px; line-height: 1.6; }
        .info strong { display: inline-block; min-width: 100px; }
        .footer { margin-top: 32px; text-align: center; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 16px; }
        .badge { display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 11px; font-weight: 600; }
        .badge-paid { background: #d4edda; color: #155724; }
        .badge-partial { background: #fff3cd; color: #856404; }
        @media print { body { margin: 20px; } .no-print { display: none; } }
      </style>
      </head>
      <body>
        <div class="header">
          <h1>${buildingName || 'RentiHub'}</h1>
          <p>Payment Receipt</p>
        </div>
        <div class="receipt-no">Receipt #${payment.receiptId}</div>
        <div class="info">
          <strong>Tenant:</strong> ${tenant || payment.tenantName}<br>
          <strong>Unit:</strong> ${unit}<br>
          <strong>Floor:</strong> ${floor}<br>
          <strong>Date:</strong> ${payment.date || '—'}<br>
          <strong>Status:</strong> <span class="badge ${payment.status === 'Paid' ? 'badge-paid' : 'badge-partial'}">${payment.status}</span>
        </div>
        <table>
          <tr><td>Payment Method</td><td>${payment.method || 'Cash'}</td></tr>
          <tr><td>Description</td><td>Rent payment — ${unit}</td></tr>
          <tr class="total-row"><td>Total Paid</td><td>UGX ${(payment.amount || 0).toLocaleString()}</td></tr>
        </table>
        <div class="footer">
          <p>Generated by RentiHub &middot; ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })}</p>
          <p>Thank you for your payment</p>
        </div>
        <script>window.print()</script>
      </body>
      </html>
    `)
    printWindow.document.close()
  }

  const balanceAfter = Math.max(0, (payment.previousBalance || 0) - (payment.amount || 0))

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose() }}>
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg mx-4 overflow-hidden" onClick={(e) => e.stopPropagation()}>
        <div className="bg-gradient-to-r from-primary to-primary-300 px-6 py-5 text-white flex items-center justify-between">
          <div>
            <h2 className="text-base font-bold tracking-wide">{buildingName || 'RentiHub'}</h2>
            <p className="text-xs text-white/70 mt-0.5">Payment Receipt</p>
          </div>
          <div className="text-right">
            <p className="text-[10px] text-white/60 uppercase tracking-wider">Receipt #</p>
            <p className="text-sm font-mono font-semibold">{payment.receiptId}</p>
          </div>
        </div>

        <div className="p-6 space-y-5">
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <p className="text-[11px] text-on-surface-dim uppercase tracking-wide font-semibold mb-0.5">Tenant</p>
              <p className="font-medium text-on-surface">{tenant || payment.tenantName}</p>
            </div>
            <div className="text-right">
              <p className="text-[11px] text-on-surface-dim uppercase tracking-wide font-semibold mb-0.5">Date</p>
              <p className="text-on-surface">{payment.date || '—'}</p>
            </div>
            <div>
              <p className="text-[11px] text-on-surface-dim uppercase tracking-wide font-semibold mb-0.5">Unit</p>
              <p className="text-on-surface">{unit}</p>
            </div>
            <div className="text-right">
              <p className="text-[11px] text-on-surface-dim uppercase tracking-wide font-semibold mb-0.5">Floor</p>
              <p className="text-on-surface">{floor}</p>
            </div>
          </div>

          <div className="border-t border-outline pt-4">
            <div className="space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-on-surface-muted">Payment Method</span>
                <span className="font-medium text-on-surface">{payment.method || 'Cash'}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-on-surface-muted">Status</span>
                <span className={`text-xs font-semibold ${payment.status === 'Paid' ? 'text-status-paid' : 'text-status-unpaid'}`}>{payment.status}</span>
              </div>
              {payment.previousBalance !== undefined && (
                <div className="flex justify-between text-sm">
                  <span className="text-on-surface-muted">Balance Before</span>
                  <span className="text-on-surface">UGX {(payment.previousBalance || 0).toLocaleString()}</span>
                </div>
              )}
              <div className="flex justify-between text-lg font-bold text-on-surface border-t border-outline pt-2 mt-2">
                <span>Amount Paid</span>
                <span className="text-primary">UGX {(payment.amount || 0).toLocaleString()}</span>
              </div>
              {payment.previousBalance !== undefined && (
                <div className="flex justify-between text-sm pt-1">
                  <span className="text-on-surface-muted">Outstanding Balance</span>
                  <span className={balanceAfter > 0 ? 'text-status-unpaid font-medium' : 'text-status-paid font-medium'}>
                    {balanceAfter > 0 ? `UGX ${balanceAfter.toLocaleString()}` : 'Cleared'}
                  </span>
                </div>
              )}
            </div>
          </div>

          <div className="text-center text-[11px] text-on-surface-dim italic border-t border-outline pt-4">
            Thank you for your payment
          </div>
        </div>

        <div className="flex items-center justify-end gap-2 px-6 pb-5">
          <button onClick={onClose}
            className="px-4 py-2.5 text-sm font-medium text-on-surface-muted hover:bg-surface-container rounded-lg transition-colors">
            Close
          </button>
          <button onClick={handlePrint}
            className="px-5 py-2.5 text-sm font-semibold text-white bg-primary hover:bg-primary-600 rounded-lg shadow-card transition-colors inline-flex items-center gap-1.5">
            <span className="material-symbols-outlined text-base">print</span>
            Print Receipt
          </button>
        </div>
      </div>
    </div>
  )
}
