import { STELLAR_EXPLORER_URL } from '../lib/stellar'

export default function PaymentReceipt({ payment, tenant, floor, unit, buildingName, onClose }) {
  const prevBal = payment.previousBalance ?? 0
  const amount = payment.amount || 0
  const newBal = prevBal - amount
  const isCredit = newBal < 0
  const isSettled = newBal === 0
  const statusText = isCredit ? 'Overpaid / Credit' : isSettled ? 'Settled' : 'Partially Paid'
  const statusColor = isCredit ? 'text-blue-600' : isSettled ? 'text-status-paid' : 'text-status-unpaid'

  const handlePrint = () => {
    const printWindow = window.open('', '_blank')
    if (!printWindow) return
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head><title>Receipt ${payment.receiptId}</title>
      <style>
        body { font-family: 'Segoe UI', system-ui, sans-serif; max-width: 600px; margin: 40px auto; padding: 0 20px; color: #1a1a2e; }
        .header { text-align: center; border-bottom: 2px solid #1a1a2e; padding-bottom: 16px; margin-bottom: 24px; }
        .header h1 { margin: 0; font-size: 22px; letter-spacing: 1px; }
        .header p { margin: 4px 0 0; color: #666; font-size: 13px; }
        .receipt-no { text-align: right; font-size: 13px; color: #666; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; }
        td { padding: 7px 0; font-size: 14px; }
        td:last-child { text-align: right; font-weight: 500; }
        .label { color: #888; }
        .divider td { border-top: 1px solid #ddd; }
        .total td { border-top: 2px solid #1a1a2e; padding-top: 10px; font-weight: 700; font-size: 16px; }
        .total td:last-child { color: #2563eb; }
        .info { margin: 20px 0; padding: 14px; background: #f8f9fa; border-radius: 8px; font-size: 13px; line-height: 1.6; }
        .info strong { display: inline-block; min-width: 100px; }
        .footer { margin-top: 32px; text-align: center; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 16px; }
        .status-paid { color: #155724; font-weight: 600; }
        .status-unpaid { color: #dc3545; font-weight: 600; }
        .status-credit { color: #2563eb; font-weight: 600; }
        @media print { body { margin: 20px; } }
      </style>
      </head>
      <body>
        <div class="header">
          <h1>${buildingName || 'RentiHub'}</h1>
          <p>Payment Receipt</p>
        </div>
        <div class="receipt-no">Receipt #${payment.receiptId}</div>
        <div class="info">
          <strong>Tenant:</strong> ${tenant || payment.tenantName}<br>
          <strong>Unit:</strong> ${unit}<br>
          <strong>Floor:</strong> ${floor}<br>
          <strong>Date:</strong> ${payment.date || '—'}<br>
          <strong>Status:</strong> ${payment.status}
        </div>
        <table>
          <tr><td class="label">Payment Method</td><td>${payment.method || 'Cash'}</td></tr>
          <tr><td class="label">Description</td><td>Rent payment — ${unit}</td></tr>
          <tr class="divider"><td colspan="2"></td></tr>
          <tr><td class="label">Balance Before</td><td>UGX ${prevBal.toLocaleString()}</td></tr>
          <tr class="total"><td>Amount Paid</td><td>UGX ${amount.toLocaleString()}</td></tr>
          <tr><td class="label">Balance After</td><td class="${isCredit ? 'status-credit' : newBal > 0 ? 'status-unpaid' : ''}">${isCredit ? '−UGX ' + Math.abs(newBal).toLocaleString() + ' (Credit)' : newBal > 0 ? 'UGX ' + newBal.toLocaleString() + ' (Due)' : 'UGX 0 (Cleared)'}</td></tr>
        </table>
        ${payment.stellarTxHash ? `<div class="footer"><p>Verified on Stellar · ${STELLAR_EXPLORER_URL}/${payment.stellarTxHash}</p></div>` : ''}
        <div class="footer">
          <p>Generated by RentiHub · ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })}</p>
          <p>Thank you for your payment</p>
        </div>
        <script>window.print()</script>
      </body>
      </html>
    `)
    printWindow.document.close()
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose() }}>
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg mx-4 flex flex-col max-h-[90vh]" onClick={(e) => e.stopPropagation()}>
        <div className="bg-gradient-to-r from-primary to-primary-300 px-6 py-5 text-white shrink-0 flex items-center justify-between rounded-t-2xl">
          <div>
            <h2 className="text-base font-bold tracking-wide">{buildingName || 'RentiHub'}</h2>
            <p className="text-xs text-white/70 mt-0.5">Payment Receipt</p>
          </div>
          <div className="text-right">
            <p className="text-[10px] text-white/60 uppercase tracking-wider">Receipt #</p>
            <p className="text-sm font-mono font-semibold">{payment.receiptId}</p>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto px-6 py-5 space-y-5">
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <p className="text-[11px] text-on-surface-dim uppercase tracking-wide font-semibold mb-0.5">Tenant</p>
              <p className="font-medium text-on-surface">{tenant || payment.tenantName}</p>
            </div>
            <div className="text-right">
              <p className="text-[11px] text-on-surface-dim uppercase tracking-wide font-semibold mb-0.5">Date</p>
              <p className="text-on-surface">{payment.date || '—'}</p>
            </div>
            <div>
              <p className="text-[11px] text-on-surface-dim uppercase tracking-wide font-semibold mb-0.5">Unit</p>
              <p className="text-on-surface">{unit}</p>
            </div>
            <div className="text-right">
              <p className="text-[11px] text-on-surface-dim uppercase tracking-wide font-semibold mb-0.5">Floor</p>
              <p className="text-on-surface">{floor}</p>
            </div>
          </div>

          <div className="bg-surface-container/50 rounded-xl p-4 space-y-3">
            <div className="flex justify-between text-sm">
              <span className="text-on-surface-muted">Payment Method</span>
              <span className="font-medium text-on-surface">{payment.method || 'Cash'}</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-on-surface-muted">Status</span>
              <span className={`text-xs font-semibold ${payment.status === 'Paid' ? 'text-status-paid' : 'text-status-unpaid'}`}>{payment.status}</span>
            </div>

            <div className="border-t border-outline/50 pt-3 mt-1 space-y-3">
              <div className="flex justify-between text-sm">
                <span className="text-on-surface-muted">Balance Before</span>
                <span className="font-medium text-on-surface">UGX {prevBal.toLocaleString()}</span>
              </div>
              <div className="flex justify-between text-lg font-bold pt-3 mt-1 border-t-2 border-primary/20 -mx-4 px-4">
                <span>Amount Paid</span>
                <span className="text-primary">UGX {amount.toLocaleString()}</span>
              </div>
              <div className="flex justify-between text-sm pt-1">
                <span className="text-on-surface-muted">Balance After</span>
                <span className={`font-semibold ${isCredit ? 'text-blue-600' : newBal > 0 ? 'text-status-unpaid' : 'text-status-paid'}`}>
                  {isCredit
                    ? `−UGX ${Math.abs(newBal).toLocaleString()} (Prepaid)`
                    : newBal > 0
                      ? `UGX ${newBal.toLocaleString()} (Due)`
                      : 'UGX 0 (Cleared)'}
                </span>
              </div>
            </div>
          </div>

          {newBal > 0 && (
            <div className="flex items-start gap-2.5 p-3.5 bg-red-50 border border-red-100 rounded-xl">
              <span className="material-symbols-outlined text-status-unpaid text-base shrink-0 mt-0.5">warning</span>
              <div>
                <p className="text-xs font-semibold text-red-700">Outstanding Balance: UGX {newBal.toLocaleString()}</p>
                <p className="text-[11px] text-red-600 mt-0.5 leading-relaxed">This tenant still owes UGX {newBal.toLocaleString()} after this payment.</p>
              </div>
            </div>
          )}

          {isCredit && (
            <div className="flex items-start gap-2.5 p-3.5 bg-blue-50 border border-blue-100 rounded-xl">
              <span className="material-symbols-outlined text-blue-500 text-base shrink-0 mt-0.5">account_balance_wallet</span>
              <div>
                <p className="text-xs font-semibold text-blue-700">Prepaid Credit: UGX {Math.abs(newBal).toLocaleString()}</p>
                <p className="text-[11px] text-blue-600 mt-0.5 leading-relaxed">This amount will be applied to the next month's rent automatically.</p>
              </div>
            </div>
          )}

          {isSettled && (
            <div className="flex items-start gap-2.5 p-3.5 bg-emerald-50 border border-emerald-100 rounded-xl">
              <span className="material-symbols-outlined text-emerald-600 text-base shrink-0 mt-0.5">check_circle</span>
              <div>
                <p className="text-xs font-semibold text-emerald-700">Settled</p>
                <p className="text-[11px] text-emerald-600 mt-0.5 leading-relaxed">This tenant is fully paid up.</p>
              </div>
            </div>
          )}

          {payment.stellarTxHash ? (
            <div className="bg-emerald-50 border border-emerald-200 rounded-xl p-3.5 flex items-start gap-2.5">
              <div className="w-7 h-7 rounded-full bg-emerald-100 flex items-center justify-center shrink-0 mt-0.5">
                <span className="material-symbols-outlined text-emerald-600 text-sm">verified</span>
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-xs font-semibold text-emerald-800">Verified on Stellar Blockchain</p>
                <p className="text-[10px] text-emerald-600 mt-0.5 leading-relaxed">This receipt hash is cryptographically anchored to the Stellar ledger — tamper-proof and independently verifiable.</p>
                <a href={`${STELLAR_EXPLORER_URL}/${payment.stellarTxHash}`} target="_blank" rel="noopener noreferrer"
                  className="inline-flex items-center gap-1 text-[11px] font-medium text-emerald-700 hover:text-emerald-800 mt-2 underline underline-offset-2">
                  View on Stellar Explorer
                  <span className="material-symbols-outlined text-[12px]">open_in_new</span>
                </a>
              </div>
            </div>
          ) : (
            <div className="bg-amber-50 border border-amber-200 rounded-xl p-3.5 flex items-center gap-3">
              <div className="w-6 h-6 rounded-full bg-amber-100 flex items-center justify-center shrink-0">
                <span className="material-symbols-outlined text-amber-500 text-xs">hourglass_top</span>
              </div>
              <p className="text-[11px] text-amber-700 leading-relaxed"><strong>Notarizing...</strong> This receipt is being anchored to the Stellar blockchain for tamper-proof verification.</p>
            </div>
          )}

          <p className="text-center text-[11px] text-on-surface-dim italic pt-2">Thank you for your payment</p>
        </div>

        <div className="shrink-0 flex items-center justify-end gap-2.5 px-6 py-4 border-t border-outline bg-surface-container/30 rounded-b-2xl">
          <button onClick={onClose}
            className="h-10 px-5 text-sm font-medium text-on-surface-muted hover:text-on-surface hover:bg-surface-container-high rounded-xl transition-colors">
            Close
          </button>
          <button onClick={handlePrint}
            className="h-10 px-5 text-sm font-semibold text-white bg-primary hover:bg-primary-600 rounded-xl shadow-card transition-colors inline-flex items-center gap-2">
            <span className="material-symbols-outlined text-base">print</span>
            Print Receipt
          </button>
        </div>
      </div>
    </div>
  )
}
