export default function PaymentReceipt({ payment, tenant, floor, unit, buildingName, onClose }) {
  const prevBal = payment.previousBalance ?? 0
  const amount = payment.amount || 0
  const newBal = prevBal - amount
  const isCredit = newBal < 0
  const isOverdue = prevBal > 0
  const statusText = isCredit ? 'Overpaid / Credit' : isOverdue ? 'Partially Paid' : 'Settled'
  const statusColor = isCredit ? 'text-blue-600' : isOverdue ? 'text-status-unpaid' : 'text-status-paid'

  const handlePrint = () => {
    const printWindow = window.open('', '_blank')
    if (!printWindow) return
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head><title>Receipt ${payment.receiptId}</title>
      <style>
        body { font-family: 'Segoe UI', system-ui, sans-serif; max-width: 600px; margin: 40px auto; padding: 0 20px; color: #1a1a2e; }
        .header { text-align: center; border-bottom: 2px solid #1a1a2e; padding-bottom: 16px; margin-bottom: 24px; }
        .header h1 { margin: 0; font-size: 22px; letter-spacing: 1px; }
        .header p { margin: 4px 0 0; color: #666; font-size: 13px; }
        .receipt-no { text-align: right; font-size: 13px; color: #666; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; }
        td { padding: 7px 0; font-size: 14px; }
        td:last-child { text-align: right; font-weight: 500; }
        .label { color: #888; }
        .divider td { border-top: 1px solid #ddd; }
        .total td { border-top: 2px solid #1a1a2e; padding-top: 10px; font-weight: 700; font-size: 16px; }
        .total td:last-child { color: #2563eb; }
        .info { margin: 20px 0; padding: 14px; background: #f8f9fa; border-radius: 8px; font-size: 13px; line-height: 1.6; }
        .info strong { display: inline-block; min-width: 100px; }
        .footer { margin-top: 32px; text-align: center; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 16px; }
        .status-paid { color: #155724; font-weight: 600; }
        .status-unpaid { color: #dc3545; font-weight: 600; }
        .status-credit { color: #2563eb; font-weight: 600; }
        @media print { body { margin: 20px; } .no-print { display: none; } }
      </style>
      </head>
      <body>
        <div class="header">
          <h1>${buildingName || 'RentiHub'}</h1>
          <p>Payment Receipt</p>
        </div>
        <div class="receipt-no">Receipt #${payment.receiptId}</div>
        <div class="info">
          <strong>Tenant:</strong> ${tenant || payment.tenantName}<br>
          <strong>Unit:</strong> ${unit}<br>
          <strong>Floor:</strong> ${floor}<br>
          <strong>Date:</strong> ${payment.date || '—'}<br>
          <strong>Status:</strong> ${payment.status}
        </div>
        <table>
          <tr><td class="label">Payment Method</td><td>${payment.method || 'Cash'}</td></tr>
          <tr><td class="label">Description</td><td>Rent payment — ${unit}</td></tr>
          <tr class="divider"><td colspan="2"></td></tr>
          <tr><td class="label">Balance Before</td><td>UGX ${prevBal.toLocaleString()}</td></tr>
          <tr class="total"><td>Amount Paid</td><td>UGX ${amount.toLocaleString()}</td></tr>
          <tr><td class="label">Balance After</td><td class="${isCredit ? 'status-credit' : isOverdue ? 'status-unpaid' : ''}">${isCredit ? '−UGX ' + Math.abs(newBal).toLocaleString() + ' (Credit)' : isOverdue ? 'UGX ' + newBal.toLocaleString() + ' (Due)' : 'UGX 0 (Cleared)'}</td></tr>
        </table>
        <div class="footer">
          <p>Generated by RentiHub &middot; ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })}</p>
          <p>Thank you for your payment</p>
        </div>
        <script>window.print()</script>
      </body>
      </html>
    `)
    printWindow.document.close()
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose() }}>
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg mx-4 overflow-hidden" onClick={(e) => e.stopPropagation()}>
        <div className="bg-gradient-to-r from-primary to-primary-300 px-6 py-5 text-white flex items-center justify-between">
          <div>
            <h2 className="text-base font-bold tracking-wide">{buildingName || 'RentiHub'}</h2>
            <p className="text-xs text-white/70 mt-0.5">Payment Receipt</p>
          </div>
          <div className="text-right">
            <p className="text-[10px] text-white/60 uppercase tracking-wider">Receipt #</p>
            <p className="text-sm font-mono font-semibold">{payment.receiptId}</p>
          </div>
        </div>

        <div className="p-6 space-y-5">
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <p className="text-[11px] text-on-surface-dim uppercase tracking-wide font-semibold mb-0.5">Tenant</p>
              <p className="font-medium text-on-surface">{tenant || payment.tenantName}</p>
            </div>
            <div className="text-right">
              <p className="text-[11px] text-on-surface-dim uppercase tracking-wide font-semibold mb-0.5">Date</p>
              <p className="text-on-surface">{payment.date || '—'}</p>
            </div>
            <div>
              <p className="text-[11px] text-on-surface-dim uppercase tracking-wide font-semibold mb-0.5">Unit</p>
              <p className="text-on-surface">{unit}</p>
            </div>
            <div className="text-right">
              <p className="text-[11px] text-on-surface-dim uppercase tracking-wide font-semibold mb-0.5">Floor</p>
              <p className="text-on-surface">{floor}</p>
            </div>
          </div>

          <div className="border-t border-outline pt-4">
            <div className="space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-on-surface-muted">Payment Method</span>
                <span className="font-medium text-on-surface">{payment.method || 'Cash'}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-on-surface-muted">Status</span>
                <span className={`text-xs font-semibold ${payment.status === 'Paid' ? 'text-status-paid' : 'text-status-unpaid'}`}>{payment.status}</span>
              </div>

              <div className="border-t border-outline/50 pt-3 mt-3 space-y-2">
                <div className="flex justify-between text-sm">
                  <span className="text-on-surface-muted">Balance Before</span>
                  <span className="font-medium text-on-surface">UGX {prevBal.toLocaleString()}</span>
                </div>

                <div className={`flex justify-between text-lg font-bold border-t border-outline pt-2 mt-1 ${isOverdue ? 'border-status-unpaid/30' : ''}`}>
                  <span>Amount Paid</span>
                  <span className="text-primary">UGX {amount.toLocaleString()}</span>
                </div>

                <div className="flex justify-between pt-1">
                  <span className="text-on-surface-muted text-sm">Balance After</span>
                  <span className={`text-sm font-semibold ${isCredit ? 'text-blue-600' : newBal > 0 ? 'text-status-unpaid' : 'text-status-paid'}`}>
                    {isCredit
                      ? `−UGX ${Math.abs(newBal).toLocaleString()} (Prepaid)`
                      : newBal > 0
                        ? `UGX ${newBal.toLocaleString()} (Due)`
                        : 'UGX 0 (Cleared)'}
                  </span>
                </div>
              </div>

              {isOverdue && !isCredit && (
                <div className="flex items-start gap-2 p-3 bg-red-50 border border-red-100 rounded-lg mt-2">
                  <span className="material-symbols-outlined text-status-unpaid text-base shrink-0 mt-0.5">warning</span>
                  <p className="text-xs text-red-700">
                    <strong>Outstanding:</strong> UGX {newBal.toLocaleString()} remains unpaid.
                    Tenant still owes UGX {newBal.toLocaleString()} for this period.
                  </p>
                </div>
              )}

              {isCredit && (
                <div className="flex items-start gap-2 p-3 bg-blue-50 border border-blue-100 rounded-lg mt-2">
                  <span className="material-symbols-outlined text-blue-500 text-base shrink-0 mt-0.5">account_balance_wallet</span>
                  <p className="text-xs text-blue-700">
                    <strong>Prepaid Credit:</strong> UGX {Math.abs(newBal).toLocaleString()} available.
                    This amount will be applied to the next month's rent automatically.
                  </p>
                </div>
              )}

              {!isOverdue && !isCredit && (
                <div className="flex items-start gap-2 p-3 bg-green-50 border border-green-100 rounded-lg mt-2">
                  <span className="material-symbols-outlined text-status-paid text-base shrink-0 mt-0.5">check_circle</span>
                  <p className="text-xs text-green-700">
                    <strong>Settled.</strong> Tenant is fully paid up for this period.
                  </p>
                </div>
              )}
            </div>
          </div>

          <div className="text-center text-[11px] text-on-surface-dim italic border-t border-outline pt-4">
            Thank you for your payment
          </div>
        </div>

        <div className="flex items-center justify-end gap-2 px-6 pb-5">
          <button onClick={onClose}
            className="px-4 py-2.5 text-sm font-medium text-on-surface-muted hover:bg-surface-container rounded-lg transition-colors">
            Close
          </button>
          <button onClick={handlePrint}
            className="px-5 py-2.5 text-sm font-semibold text-white bg-primary hover:bg-primary-600 rounded-lg shadow-card transition-colors inline-flex items-center gap-1.5">
            <span className="material-symbols-outlined text-base">print</span>
            Print Receipt
          </button>
        </div>
      </div>
    </div>
  )
}
